### ISSUE TITLE
[Error] corrupted size vs. prev_size in fastbins upon quitting game

### ISSUE THREAD

**Issue by Blzut3** [ECWolfEngine/ECWolf#274]
**[Original report](https://bitbucket.org/ecwolf/ecwolf/issues/274) by Trung Lê (Bitbucket: [rbj](https://bitbucket.org/rbj), GitHub: [rbj](https://github.com/rbj)).**

----------------------------------------

The game runs fine however I got following error upon quitting it:  

> $ ./build/final/ecwolf  
> ReadConfig: Reading the Configuration.  
> IWad: Selecting base game data.  
> W\_Init: Init WADfiles.  
> adding /home/tle/src/ecwolf/build/final/ecwolf.pk3, 99 lumps  
> adding /home/tle/src/ecwolf/build/final/AUDIOT.WL1, 288 lumps  
> adding /home/tle/src/ecwolf/build/final/GAMEMAPS.WL1, 20 lumps  
> adding /home/tle/src/ecwolf/build/final/VGAGRAPH.WL1, 156 lumps  
> adding /home/tle/src/ecwolf/build/final/VSWAP.WL1, 588 lumps  
> InitGame: Setting up the game...  
> SDL\_Init: Using SDL 2.0.12  
> VL\_ReadPalette: Setting up the Palette...  
> ClassDef: Loading actor definitions.  
> S\_Init: Opened audio: 44100Hz \(2 channels\)  
> S\_Init: Reading SNDINFO defintions.  
> S\_Init: Reading SNDSEQ defintions.  
> US\_Startup: Starting the User Manager.  
> CreateMenus: Preparing the menu system...  
> DemoLoop: Starting the game loop...  
> corrupted size vs. prev\_size in fastbins  
> Aborted \(core dumped\)

  
Below is the stacktrace:

‌

> $ gdb ./build/final/ecwolf  
> GNU gdb \(GDB\) Fedora 9.1-3.fc32  
> Copyright \(C\) 2020 Free Software Foundation, Inc.  
> License GPLv3\+: GNU GPL version 3 or later <[http://gnu.org/licenses/gpl.html](http://gnu.org/licenses/gpl.html)>  
> This is free software: you are free to change and redistribute it.  
> There is NO WARRANTY, to the extent permitted by law.  
> Type "show copying" and "show warranty" for details.  
> This GDB was configured as "ppc64le-redhat-linux-gnu".  
> Type "show configuration" for configuration details.  
> For bug reporting instructions, please see:  
> <[http://www.gnu.org/software/gdb/bugs/](http://www.gnu.org/software/gdb/bugs/).>  
> Find the GDB manual and other documentation resources online at:  
> <[http://www.gnu.org/software/gdb/documentation/](http://www.gnu.org/software/gdb/documentation/).>
>
> For help, type "help".  
> Type "apropos word" to search for commands related to "word"...  
> Reading symbols from ./build/final/ecwolf...  
> \(No debugging symbols found in ./build/final/ecwolf\)  
> \(gdb\) r  
> Starting program: /home/tle/src/ecwolf/build/final/ecwolf  
> Missing separate debuginfo for /lib64/libSDL2\_mixer-2.0.so.0  
> Try: dnf --enablerepo='_debug_' install /usr/lib/debug/.build-id/19/b50d32c60f00917703e0c8fb7c480c01e1862d.debug  
> \[Thread debugging using libthread\_db enabled\]  
> Using host libthread\_db library "/lib64/libthread\_db.so.1".  
> \[New Thread 0x7fffe7a8ee60 \(LWP 1994208\)\]  
> \[New Thread 0x7fffe727ee60 \(LWP 1994209\)\]  
> ReadConfig: Reading the Configuration.  
> IWad: Selecting base game data.  
> W\_Init: Init WADfiles.  
> adding /home/tle/src/ecwolf/build/final/ecwolf.pk3, 99 lumps  
> adding /home/tle/src/ecwolf/build/final/AUDIOT.WL1, 288 lumps  
> adding /home/tle/src/ecwolf/build/final/GAMEMAPS.WL1, 20 lumps  
> adding /home/tle/src/ecwolf/build/final/VGAGRAPH.WL1, 156 lumps  
> adding /home/tle/src/ecwolf/build/final/VSWAP.WL1, 588 lumps  
> InitGame: Setting up the game...  
> SDL\_Init: Using SDL 2.0.12  
> VL\_ReadPalette: Setting up the Palette...  
> Missing separate debuginfo for /lib64/libXss.so.1  
> Try: dnf --enablerepo='_debug_' install /usr/lib/debug/.build-id/a8/41cba9a13a74a0fa3c1f27835f79e5e741545d.debug  
> Missing separate debuginfo for /lib64/libglapi.so.0  
> Try: dnf --enablerepo='_debug_' install /usr/lib/debug/.build-id/49/02d47febcd6350d9d3ca4a0ec37e9e785bc063.debug  
> Missing separate debuginfo for /usr/lib64/dri/radeonsi\_dri.so  
> Try: dnf --enablerepo='_debug_' install /usr/lib/debug/.build-id/57/549236b141bb59a6e74722db3b0f8ca72b12fb.debug  
> Missing separate debuginfo for /lib64/libLLVM-10.so  
> Try: dnf --enablerepo='_debug_' install /usr/lib/debug/.build-id/96/75725bffc87db9db4ad1a986e1188c41ac47e9.debug  
> \[New Thread 0x7fffe4c3ee60 \(LWP 1994211\)\]  
> \[New Thread 0x7fffd203ee60 \(LWP 1994212\)\]  
> \[New Thread 0x7fffcbffee60 \(LWP 1994213\)\]  
> \[New Thread 0x7fffd182ee60 \(LWP 1994214\)\]  
> \[New Thread 0x7fffd101ee60 \(LWP 1994215\)\]  
> \[New Thread 0x7fffd080ee60 \(LWP 1994216\)\]  
> \[New Thread 0x7fffcb7eee60 \(LWP 1994217\)\]  
> \[New Thread 0x7fffcafdee60 \(LWP 1994218\)\]  
> \[New Thread 0x7fffca7cee60 \(LWP 1994219\)\]  
> \[New Thread 0x7fffc9fbee60 \(LWP 1994220\)\]  
> \[New Thread 0x7fffc97aee60 \(LWP 1994221\)\]  
> \[New Thread 0x7fffc8f9ee60 \(LWP 1994222\)\]  
> \[New Thread 0x7fffa3ffee60 \(LWP 1994223\)\]  
> \[New Thread 0x7fffa37eee60 \(LWP 1994224\)\]  
> \[New Thread 0x7fffa2fdee60 \(LWP 1994225\)\]  
> \[New Thread 0x7fffa27cee60 \(LWP 1994226\)\]  
> \[New Thread 0x7fffa1fbee60 \(LWP 1994227\)\]  
> \[New Thread 0x7fffa17aee60 \(LWP 1994228\)\]  
> \[New Thread 0x7fffa0f9ee60 \(LWP 1994229\)\]  
> \[New Thread 0x7fff83ffee60 \(LWP 1994230\)\]  
> \[New Thread 0x7fff837eee60 \(LWP 1994231\)\]  
> \[New Thread 0x7fff82fdee60 \(LWP 1994232\)\]  
> \[New Thread 0x7fff827cee60 \(LWP 1994233\)\]  
> \[New Thread 0x7fff81fbee60 \(LWP 1994234\)\]  
> \[New Thread 0x7fff817aee60 \(LWP 1994235\)\]  
> \[New Thread 0x7fff80f9ee60 \(LWP 1994236\)\]  
> \[New Thread 0x7fff5fffee60 \(LWP 1994237\)\]  
> \[New Thread 0x7fff57ffee60 \(LWP 1994238\)\]  
> \[New Thread 0x7fff5f7eee60 \(LWP 1994239\)\]  
> \[New Thread 0x7fff5efdee60 \(LWP 1994240\)\]  
> \[New Thread 0x7fff5e7cee60 \(LWP 1994241\)\]  
> \[New Thread 0x7fff5dfbee60 \(LWP 1994242\)\]  
> \[New Thread 0x7fff5d7aee60 \(LWP 1994243\)\]  
> \[New Thread 0x7fff5cf9ee60 \(LWP 1994244\)\]  
> \[New Thread 0x7fff577eee60 \(LWP 1994245\)\]  
> \[New Thread 0x7fff56fdee60 \(LWP 1994246\)\]  
> \[New Thread 0x7fff567cee60 \(LWP 1994247\)\]  
> \[New Thread 0x7fff55fbee60 \(LWP 1994248\)\]  
> \[New Thread 0x7fff557aee60 \(LWP 1994249\)\]  
> \[New Thread 0x7fff54f9ee60 \(LWP 1994250\)\]  
> \[Thread 0x7fff54f9ee60 \(LWP 1994250\) exited\]  
> \[New Thread 0x7fff54f9ee60 \(LWP 1994251\)\]  
> \[Thread 0x7fff54f9ee60 \(LWP 1994251\) exited\]  
> \[New Thread 0x7fff54f9ee60 \(LWP 1994253\)\]  
> \[Thread 0x7fff54f9ee60 \(LWP 1994253\) exited\]  
> \[New Thread 0x7fff54f9ee60 \(LWP 1994254\)\]  
> ClassDef: Loading actor definitions.  
> Missing separate debuginfo for /lib64/libuuid.so.1  
> Try: dnf --enablerepo='_debug_' install /usr/lib/debug/.build-id/56/b70323029fa2bda12a8de11ed7d2c5ec610fef.debug  
> \[New Thread 0x7fffa01cee60 \(LWP 1994255\)\]  
> \[New Thread 0x7ffefbffee60 \(LWP 1994256\)\]  
> S\_Init: Opened audio: 44100Hz \(2 channels\)  
> S\_Init: Reading SNDINFO defintions.  
> S\_Init: Reading SNDSEQ defintions.  
> US\_Startup: Starting the User Manager.  
> CreateMenus: Preparing the menu system...  
> DemoLoop: Starting the game loop...  
> \[Thread 0x7ffefbffee60 \(LWP 1994256\) exited\]  
> \[Thread 0x7fffa01cee60 \(LWP 1994255\) exited\]  
> \[Thread 0x7fff54f9ee60 \(LWP 1994254\) exited\]  
> \[Thread 0x7fff567cee60 \(LWP 1994247\) exited\]  
> \[Thread 0x7fff557aee60 \(LWP 1994249\) exited\]  
> \[Thread 0x7fff55fbee60 \(LWP 1994248\) exited\]  
> \[Thread 0x7fff56fdee60 \(LWP 1994246\) exited\]  
> \[Thread 0x7fff577eee60 \(LWP 1994245\) exited\]  
> \[Thread 0x7fff5cf9ee60 \(LWP 1994244\) exited\]  
> \[Thread 0x7fff5d7aee60 \(LWP 1994243\) exited\]  
> \[Thread 0x7fff5dfbee60 \(LWP 1994242\) exited\]  
> \[Thread 0x7fff5e7cee60 \(LWP 1994241\) exited\]  
> \[Thread 0x7fff5efdee60 \(LWP 1994240\) exited\]  
> \[Thread 0x7fff5f7eee60 \(LWP 1994239\) exited\]  
> \[Thread 0x7fff5fffee60 \(LWP 1994237\) exited\]  
> \[Thread 0x7fff80f9ee60 \(LWP 1994236\) exited\]  
> \[Thread 0x7fffc8f9ee60 \(LWP 1994222\) exited\]  
> \[Thread 0x7fff57ffee60 \(LWP 1994238\) exited\]  
> \[Thread 0x7fffa0f9ee60 \(LWP 1994229\) exited\]  
> \[Thread 0x7fffa3ffee60 \(LWP 1994223\) exited\]  
> \[Thread 0x7fff83ffee60 \(LWP 1994230\) exited\]  
> \[Thread 0x7fff817aee60 \(LWP 1994235\) exited\]  
> \[Thread 0x7fff827cee60 \(LWP 1994233\) exited\]  
> \[Thread 0x7fff81fbee60 \(LWP 1994234\) exited\]  
> \[Thread 0x7fff82fdee60 \(LWP 1994232\) exited\]  
> \[Thread 0x7fff837eee60 \(LWP 1994231\) exited\]  
> \[Thread 0x7fffa17aee60 \(LWP 1994228\) exited\]  
> \[Thread 0x7fffa1fbee60 \(LWP 1994227\) exited\]  
> \[Thread 0x7fffa27cee60 \(LWP 1994226\) exited\]  
> \[Thread 0x7fffa2fdee60 \(LWP 1994225\) exited\]  
> \[Thread 0x7fffa37eee60 \(LWP 1994224\) exited\]  
> \[Thread 0x7fffc97aee60 \(LWP 1994221\) exited\]  
> \[Thread 0x7fffc9fbee60 \(LWP 1994220\) exited\]  
> \[Thread 0x7fffca7cee60 \(LWP 1994219\) exited\]  
> \[Thread 0x7fffcafdee60 \(LWP 1994218\) exited\]  
> \[Thread 0x7fffcb7eee60 \(LWP 1994217\) exited\]  
> \[Thread 0x7fffd080ee60 \(LWP 1994216\) exited\]  
> \[Thread 0x7fffd182ee60 \(LWP 1994214\) exited\]  
> \[Thread 0x7fffcbffee60 \(LWP 1994213\) exited\]  
> \[Thread 0x7fffd203ee60 \(LWP 1994212\) exited\]  
> \[Thread 0x7fffd101ee60 \(LWP 1994215\) exited\]  
> \[Thread 0x7fffe4c3ee60 \(LWP 1994211\) exited\]  
> corrupted size vs. prev\_size in fastbins  
> --Type <RET> for more, q to quit, c to continue without paging--
>
> Thread 1 "ecwolf" received signal SIGABRT, Aborted.  
> 0x00007ffff60f9238 in \_\_libc\_signal\_restore\_set \(set=0x7fffffffcf98\) at ../sysdeps/unix/sysv/linux/internal-signals.h:86  
> 86	  INTERNAL\_SYSCALL\_CALL \(rt\_sigprocmask, err, SIG\_SETMASK, set, NULL,  
> \(gdb\) bt  
> \#0  0x00007ffff60f9238 in \_\_libc\_signal\_restore\_set \(set=0x7fffffffcf98\) at ../sysdeps/unix/sysv/linux/internal-signals.h:86  
> \#1  \_\_GI\_raise \(sig=<optimized out>\) at ../sysdeps/unix/sysv/linux/raise.c:48  
> \#2  0x00007ffff60d7c68 in \_\_GI\_abort \(\) at abort.c:79  
> \#3  0x00007ffff6148054 in \_\_libc\_message \(action=<optimized out>, fmt=<optimized out>\) at ../sysdeps/posix/libc\_fatal.c:155  
> \#4  0x00007ffff6153898 in malloc\_printerr \(str=<optimized out>, str@entry=0x7ffff626cbe0 "corrupted size vs. prev\_size in fastbins"\) at malloc.c:5347  
> \#5  0x00007ffff6154cdc in malloc\_consolidate \(av=av@entry=0x7ffff62c0bf0 <main\_arena>\) at malloc.c:4493  
> \#6  0x00007ffff6155698 in \_int\_free \(av=0x7ffff62c0bf0 <main\_arena>, p=0x107a2fa0, have\_lock=<optimized out>\) at malloc.c:4400  
> \#7  0x00007fffe5844da8 in si\_release\_all\_descriptors \(\) at /usr/lib64/dri/radeonsi\_dri.so  
> \#8  0x00007fffe57bb408 in si\_destroy\_context \(\) at /usr/lib64/dri/radeonsi\_dri.so  
> \#9  0x00007fffe5ac332c in tc\_destroy \(\) at /usr/lib64/dri/radeonsi\_dri.so  
> \#10 0x00007fffe4ef7320 in st\_destroy\_context\_priv \(\) at /usr/lib64/dri/radeonsi\_dri.so  
> \#11 0x00007fffe4ef8a78 in st\_destroy\_context \(\) at /usr/lib64/dri/radeonsi\_dri.so  
> \#12 0x00007fffe4edd938 in st\_context\_destroy \(\) at /usr/lib64/dri/radeonsi\_dri.so  
> \#13 0x00007fffe4ecdaec in dri\_destroy\_context \(\) at /usr/lib64/dri/radeonsi\_dri.so  
> \#14 0x00007fffe550fd28 in driDestroyContext \(\) at /usr/lib64/dri/radeonsi\_dri.so  
> \#15 0x00007fffe6431490 in dri3\_destroy\_context \(context=0x1073f070\) at ../src/glx/dri3\_glx.c:181  
> \#16 0x00007fffe640a794 in glXDestroyContext \(ctx=0x1073f070, dpy=0x106d5f10\) at ../src/glx/glxcmds.c:511  
> \#17 glXDestroyContext \(dpy=0x106d5f10, ctx=0x1073f070\) at ../src/glx/glxcmds.c:492  
> \#18 0x00007fffe65c91cc in glXDestroyContext \(dpy=0x106d5f10, context=0x1073f070\) at libglx.c:332  
> \#19 0x00007ffff69d0880 in X11\_GL\_DeleteContext \(\_this=<optimized out>, context=<optimized out>\)  
> at /usr/src/debug/SDL2-2.0.12-1.fc32.ppc64le/src/video/x11/SDL\_x11opengl.c:944  
> \#20 0x00007ffff69aa454 in SDL\_GL\_DeleteContext\_REAL \(context=0x1073f070\) at /usr/src/debug/SDL2-2.0.12-1.fc32.ppc64le/src/video/SDL\_video.c:3655  
> \#21 SDL\_GL\_DeleteContext\_REAL \(context=0x1073f070\) at /usr/src/debug/SDL2-2.0.12-1.fc32.ppc64le/src/video/SDL\_video.c:3645  
> \#22 0x00007ffff692c160 in GL\_DestroyRenderer \(renderer=<optimized out>\) at /usr/src/debug/SDL2-2.0.12-1.fc32.ppc64le/src/render/opengl/SDL\_render\_gl.c:1504  
> \#23 0x00007ffff6928c94 in SDL\_DestroyRenderer\_REAL \(renderer=0x107cdd50\) at /usr/src/debug/SDL2-2.0.12-1.fc32.ppc64le/src/render/SDL\_render.c:3250  
> \#24 0x00007ffff68fc318 in SDL\_DestroyRenderer \(a=<optimized out>\) at /usr/src/debug/SDL2-2.0.12-1.fc32.ppc64le/src/dynapi/SDL\_dynapi\_procs.h:379  
> \#25 0x000000001017baa4 in SDLFB::~SDLFB\(\) \(\)  
> \#26 0x000000001017bb54 in SDLFB::~SDLFB\(\) \(\)  
> \#27 0x000000001017abf4 in I\_ShutdownGraphics\(\) \(\)  
> \#28 0x00000000101d4ce4 in CallTerminateFunctions\(\) \(\)  
> \#29 0x00007ffff60fd0c4 in \_\_run\_exit\_handlers  
> \(status=<optimized out>, listp=0x7ffff62c0810 <\_\_exit\_funcs>, run\_list\_atexit=run\_list\_atexit@entry=true, run\_dtors=run\_dtors@entry=true\) at exit.c:108  
> \#30 0x00007ffff60fd308 in \_\_GI\_exit \(status=<optimized out>\) at exit.c:139  
> \#31 0x00000000101d2c30 in Quit\(char const\*, ...\) \(\)  
> \#32 0x00000000101d5750 in QuitGame\(int\) \(\)  
> \#33 0x0000000010161f98 in MenuItem::activate\(\) \(\)  
> \#34 0x00000000101673e4 in Menu::handle\(\) \(\)  
> \#35 0x00000000101d9c0c in US\_ControlPanel\(int\) \(\)  
> \#36 0x00000000101d342c in DemoLoop\(\) \(\)  
> \#37 0x00000000101d4f8c in WL\_Main\(int, char\*\*\) \(\)  
> --Type <RET> for more, q to quit, c to continue without paging--  
> \#38 0x00000000101d5188 in main \(\)  
> \(gdb\) c  
> Continuing.  
> \[Thread 0x7fffe727ee60 \(LWP 1994209\) exited\]  
> \[Thread 0x7fffe7a8ee60 \(LWP 1994208\) exited\]
>
> Program terminated with signal SIGABRT, Aborted.  
> The program no longer exists.

‌

**Comment by Blzut3** [comment]
Duplicate of #273.
